"""Preprocess the raw Omni OpenAPI spec for openapi-python-client.

The spec is generated by zod-to-openapi, which emits two constructs the
generator can't handle:

1. `allOf: [<schema>, {description: ...}]` wrappers produced by zod's
   `.describe()` — collapsed to the inner schema.
2. A handful of deeply recursive document-layout / visualization schemas —
   stubbed out as free-form objects so the rest of the client still generates
   with full endpoint coverage. Callers pass/receive plain dicts for these.

Usage: python scripts/preprocess_spec.py spec/openapi.json spec/openapi.processed.json
"""

import json
import sys

OBJ = {"type": "object", "additionalProperties": True}
ARR = {"type": "array", "items": {"type": "object", "additionalProperties": True}}

# Schemas replaced with free-form stubs (recursive or too dynamic to model).
STUBS = {
    "JsonValue": OBJ,
    "GridContainer": OBJ,
    "StackContainer": OBJ,
    "PageContainer": OBJ,
    "ReferenceContainer": OBJ,
    "Containers": ARR,
    "ControlReadExternal": OBJ,
    "ControlsReadExternal": OBJ,
    "ControlPatchExternal": OBJ,
    "ControlsPatchExternal": OBJ,
    "QueryPresentationReadExternal": OBJ,
    "QueryPresentationsReadExternal": OBJ,
    "QueryPresentationPatchExternal": OBJ,
    "QueryPresentationsPatchExternal": OBJ,
    "ApiVisConfig": OBJ,
    "AiSemanticQuery": OBJ,
}

ANNOTATION_KEYS = {"description", "example", "examples", "default", "deprecated", "title"}


def is_annotation_only(node):
    return isinstance(node, dict) and set(node.keys()) <= ANNOTATION_KEYS


def collapse_allof(node):
    """zod .describe() pattern: allOf: [X, {description}] -> X."""
    if isinstance(node, dict) and isinstance(node.get("allOf"), list):
        real = [m for m in node["allOf"] if not is_annotation_only(m)]
        if len(real) == 1:
            rest = {k: v for k, v in node.items() if k != "allOf"}
            new = dict(real[0])
            if "$ref" in new:
                # Siblings alongside $ref are ignored inconsistently by tools;
                # keep the bare reference.
                new = {"$ref": new["$ref"]}
            else:
                for k, v in rest.items():
                    new.setdefault(k, v)
            node.clear()
            node.update(new)


def walk(node, fn):
    if isinstance(node, dict):
        fn(node)
        for v in node.values():
            walk(v, fn)
    elif isinstance(node, list):
        for v in node:
            walk(v, fn)


def main(src, dst):
    with open(src) as f:
        spec = json.load(f)
    schemas = spec["components"]["schemas"]
    for name, stub in STUBS.items():
        if name in schemas:
            desc = schemas[name].get("description", "")
            new = dict(stub)
            new["description"] = (desc + " (Not statically modeled; use plain dicts.)").strip()
            schemas[name] = new
    walk(spec, collapse_allof)
    with open(dst, "w") as f:
        json.dump(spec, f, indent=2)
    print(f"wrote {dst}")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
